[urls]
canada = "syedabdulshameer/international-students-in-canada"
us = "webdevbadger/international-student-demographics"


[paths]
data_path= '/home/cip/ce/ix05ogym/Majid/MADE/data/'
output_table_name = "international_students_north_america"


