[urls]
canada = "syedabdulshameer/international-students-in-canada"
us = "webdevbadger/international-student-demographics"


[paths]
data_path= './data/'
output_table_name = "international_students_north_america"


