name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment (modify the version if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Print Full Path
        run: |
          echo "Full path to requirements.txt: $GITHUB_WORKSPACE/requirements.txt"
          ls -l $GITHUB_WORKSPACE/requirements.txt

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install poetry
          poetry install
          

      # Run the tests.sh script
      - name: Run Tests
        run: |
          chmod +x tests.sh
          ./project/tests.sh
        env:
          # Use GitHub secrets to handle private keys, tokens, or sensitive information
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      # Optional: Cache dependencies to improve performance
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
