name: CI Pipeline

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Print Full Path
        run: |
          echo "Full path to requirements.txt: $GITHUB_WORKSPACE/requirements.txt"
          ls -l $GITHUB_WORKSPACE/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install poetry
          poetry install
          

      - name: Run Tests
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
        
